### ISSUE TITLE
Не работает поиск фильмов и сериалов в Torrserver Client NEXT!

### ISSUE THREAD

**Issue by Seamas73** [vadyur/plugin.video.torrserve-next#1]
В Torrserver Client NEXT! не работает поиск фильмов, сериалов и торрентов.
[kodi.log](https://github.com/vadyur/plugin.video.torrserve-next/files/14136786/kodi.log)

**Comment by Seamas73** [comment]
Поправка: поиск торрентов по-прежнему не работает, поиск сериалов время от времени работает, но если находятся торренты сериала, то при попытке добавить их в список на торрсервер плагин выдаёт сообщение об ошибке и торренты в список не добавляются.
[kodi.log](https://github.com/vadyur/plugin.video.torrserve-next/files/14150077/kodi.log)

**Comment by vadyur** [comment]
Пробуй 0.7.7.1

**Comment by Seamas73** [comment]
Спасибо, теперь работает и поиск и добавление.

**Comment by vadyur** [comment]
Вот и славно
